### ISSUE TITLE
Problem with Nuts3_0

### ISSUE THREAD

**Issue by divanski** [ozwillo/ozwillo-datacore#142]
I have some problem with Nuts3_0.
When I test request to 
https://data.ozwillo-preprod.eu/dc/type/geon3:Nuts3_0?geo:country=http://data.ozwillo.com/dc/type/geocofr:Pays_0/FR 
evereting is ok and i have array whit data, but when I request to 
https://data.ozwillo-preprod.eu/dc/type/geon3:Nuts3_0?geo:country=http://data.ozwillo.com/dc/type/geocobg:C%D1%82%D1%80%D0%B0%D0%BD%D0%B0_0/BG respondet array is empty. 
This happens with all countries except in France. 
Where I wrong?

And something else. When list all countries not all have the English version of the geo:name

**Comment by mdutoo** [comment]
But as you've probably tried the example in the Playground's "Most common use cases' queries" works :) Very simple:

As said in the Playground User Manual, in preprod at https://data.ozwillo-preprod.eu/dc-ui/index.html#playgroundUserManual :
"Note that the Playground shows said key and value UNencoded in order to make it easier to enter text in the language of the user, but that developers should URI-encode them nonetheless, as Playground actually does (see its HTTP queries in a debugger such as Firebug)."

Therefore in the case of an URI, the unencoded value already has some encoded parts, so when using it as a (query) request parameter it should be encoded again (double encoded) as per HTTP specs.

So in your case you should encode it once more.

Enable Firebug in Firefox and have a look in the "Console" tab at the URL of the actual request that the Playground makes when clicking on the working example, it should rightly be:
https://data.ozwillo-preprod.eu/dc/type/geon3:Nuts3_0?geo%3Acountry=http%3A%2F%2Fdata.ozwillo.com%2Fdc%2Ftype%2Fgeocobg%3AC%25D1%2582%25D1%2580%25D0%25B0%25D0%25BD%25D0%25B0_0%2FBG&geo%3Aname=%2B

Finally, about the data problem (en geo:name in Bulgarian geo Resources etc.), I've reported it at  #62 geo & orga - have the right data.

**Comment by divanski** [comment]
Thanks Mark, now I understood
