### ISSUE TITLE
Can't Find LAU (Local administrative unit) or Municipality for Bulgaria

### ISSUE THREAD

**Issue by divanski** [ozwillo/ozwillo-datacore#143]
I get the Nuts3_0 and City in this Nuts3 but I can't find the next livel. For example LAU 2  (in Bulgarian -> Община) . Is there such administrative unit in DataCore?

**Comment by OzBruno** [comment]
Following discussion with Stanislava and Yonko, we have set the following levels and rules (in Bulgaria) : 
- Nuts 2 : not used in Bulgaria (no administrative body)
- Nuts 3 : Област
- City group : Община (geocigrbg:Община_0)
- City : НаселеноMесто

If you don't find the Община of a city it may be a data quality problem

**Comment by divanski** [comment]
I try to extract all municipalities in certain areas. 
For example:
https://data.ozwillo-preprod.eu/dc/type/geocigrbg:Община_0?geon3:Nuts3_0=http://data.ozwillo.com/dc/type/geon3bg:%D0%9E%D0%B1%D0%BB%D0%B0%D1%81%D1%82_0/BG/BG-01&geo:name=+

So it is not correct?
How should I make a request?

**Comment by mdutoo** [comment]
At least some BG cities have city groups, as can be find out in the Playground by
/dc/type/geocibg:НаселеноMесто_0?geoci:cityGroup=$exists
=>
http://data.ozwillo.com/dc/type/geocibg:%D0%9D%D0%B0%D1%81%D0%B5%D0%BB%D0%B5%D0%BD%D0%BEM%D0%B5%D1%81%D1%82%D0%BE_0/BG/BG-22/%D0%A1%D0%BE%D1%84%D0%B8%D1%8F
http://data.ozwillo.com/dc/type/geocibg:%D0%9D%D0%B0%D1%81%D0%B5%D0%BB%D0%B5%D0%BD%D0%BEM%D0%B5%D1%81%D1%82%D0%BE_0/BG/BG-01/%D0%9C%D0%B5%D1%81%D1%82%D0%B0
...
which indeed have the  "geoci:cityGroup" field.

Doing the same query (copied from Playground debug mode) in MongoDB and counting results returns :
db["geo_1.geo:Area_0"].find({"_t" : "geocibg:НаселеноMесто_0", "_p.geoci:cityGroup" : {"$exists" : true}}).count()
5244
... and 0 that don't have it. So @OzBruno , no data quality problem, all BG cities have their Община.

HOWEVER @divanski , your query last is wrong: if you run it in the Playground it says
"In type geocigrbg:Община_0, can't find field with path elements [geon3:Nuts3_0] : can't find field for first path element geon3:Nuts3_0""
and indeed, geon3:Nuts3_0 is a type and not a field (which would be written all in lower case), and more over a city group can't have a NUTS3, because (at least in France) it can be split across several of them.

If you want to "extract all municipalities in certain areas" as you say, you should not try to get CITY GROUPS but rather CITIES according to their city groups. For instance in the Playground, click on the top projects dropdown and select geo_1, then click on "stored models" and lookup geocigb and click on "RESOURCES", which gives you BG cities, then lookup geoci:cityGroup and click on the ":" that follows, which gives you the following query:
/dc/type/geocibg:НаселеноMесто_0?geoci:cityGroup=http://data.ozwillo.com/dc/type/geocigrbg:%D0%9E%D0%B1%D1%89%D0%B8%D0%BD%D0%B0_0/BG/%D0%91%D0%B0%D0%BD%D1%81%D0%BA%D0%BE
which has 8 results (as shown by clicking on the "l" button).

However you probably want postal address cities (i.e. ALSO districts in the case of Turkey) so rather transform that to:
/dc/type/addrpostci:PostalCity_0?geoci:cityGroup=http://data.ozwillo.com/dc/type/geocigrbg:%D0%9E%D0%B1%D1%89%D0%B8%D0%BD%D0%B0_0/BG/%D0%91%D0%B0%D0%BD%D1%81%D0%BA%D0%BE

**Comment by mdutoo** [comment]
However beware, geoci:cityGroup is not yet indexed, so you may not get all results and performance will be bad. @OzBruno , @divanski , is querying on this field required ?

**Comment by divanski** [comment]
Thanks @mdutoo.
This field is not required. I trying just for test. The reason is I try to limit the number of cities before request.

**Comment by mdutoo** [comment]
Great.
Well, for this purpose you can also query (postal) cities by a given NUTS3.
Anyway, I'm closing it.

**Comment by divanski** [comment]
Yes. Thanks again.
