### ISSUE TITLE
Behaviour of fulltext search on org:legalName field for organizations

### ISSUE THREAD

**Issue by bobeal** [ozwillo/ozwillo-datacore#145]
Hi,

I'm doing a fulltext search on organizations with such a query : 

```
https://plnm-dev-dc/dc/type/org:Organization_0?start=0&limit=10&org:legalName.v=$fulltextval&adrpost:country=http://data.ozwillo.com/dc/type/geocofr:Pays_0/FR
```

I was wondering why the retrieved results contain organizations whose address effectively contains "val" (whereas their legal name does not contain such characters).

**Comment by mdutoo** [comment]
Because, as browsing to the orgfr (and org) model using the "M" button shows, the odisp:name (alias of org:displayName) field (among inherited globalFields) still has dcmf:fulltext set to true, though I tried to disable it in current Master Model 2.21.

However it's OK in preprod, so I guess I've just forgotten to import model 2.21 in dev. You'll do it ?

**Comment by mdutoo** [comment]
I've just done it.
Now, the right behaviour will only happen on Resource that have been saved since. However I've just saved your own test Resource to check that it now works.
I've also deleted the remaining obsolete org:Organisation_0 and its Resources.
