### ISSUE TITLE
Access is denied when I test creation project in Playground

### ISSUE THREAD

**Issue by divanski** [ozwillo/ozwillo-datacore#147]
I follow step-by-step instruction in https://github.com/ozwillo/ozwillo-datacore/wiki/Configuring-Projects-and-Default-Rights
This is my project:
{
   "@id": "http://data.ozwillo.com/dc/type/dcmp:Project_0/altevent_0",
   "@type": [
      "dcmp:Project_0",
      "dcmpv:PointOfView_0",
      "odisp:Displayable_0"
   ],
   "dc:created": "2015-12-08T18:21:47.000+01:00",
   "dc:modified": "2015-12-09T11:46:32.965+01:00",
   "dc:contributor": "7aa76b4f-8233-4e8e-a24b-09c30b2dfb60",
   "dcmpv:name": "altevent_0",
   "dcmpv:majorVersion": 0,
   "dcmp:localVisibleProjects": [
      "http://data.ozwillo.com/dc/type/dcmp:Project_0/oasis.meta",
      "http://data.ozwillo.com/dc/type/dcmp:Project_0/geo_1",
      "http://data.ozwillo.com/dc/type/dcmp:Project_0/org_1"
   ],
   "dcmp:forkedUris": [],
   "dcmpv:unversionedName": "altevent",
   "dcmp:useCasePointOfViews": [],
   "dcmp:securityDefaults": {
      "dcms:resourceCreators": [],
      "dcms:resourceWriters": [],
      "@type": [
         "dcms:Security_0"
      ],
      "dcms:resourceCreationOwners": [],
      "dcms:isAuthentifiedReadable": true,
      "dcms:isAuthentifiedWritable": false,
      "dcms:resourceOwners": [
         "7aa76b4f-8233-4e8e-a24b-09c30b2dfb60"
      ],
      "@id": "http://data.ozwillo.com/dc/type/dcms:Security_0/dcmp:Project_0/altevent_0/dcmp:securityDefaults",
      "dcms:isAuthentifiedCreatable": true,
      "dcms:resourceReaders": []
   },
   "dcmp:frozenModelNames": [],
   "dcmp:modelLevelSecurityEnabled": false,
   "dcmp:allowedModelPrefixes": [],
   "dcmp:visibleProjectNames": [
      "altevent_0",
      "oasis.meta",
      "geo_1",
      "org_1"
   ],
   "dcmp:visibleSecurityConstraints": {
      "dcms:resourceCreators": [],
      "dcms:resourceWriters": [],
      "@type": [
         "dcms:Security_0"
      ],
      "dcms:resourceCreationOwners": [],
      "dcms:isAuthentifiedReadable": true,
      "dcms:isAuthentifiedWritable": false,
      "dcms:resourceOwners": [],
      "@id": "http://data.ozwillo.com/dc/type/dcms:Security_0/dcmp:Project_0/altevent_0/dcmp:visibleSecurityConstraints",
      "dcms:isAuthentifiedCreatable": true,
      "dcms:resourceReaders": []
   }
}

1. I check that dcmp:frozenModelNames and dcmp:allowedModelPrefixes - is empty
2. dcmp:forkedUris - empty
3. dcmp:modelLevelSecurityEnabled is false 

But I steel get "Access is denied".

Where is my mistake?

**Comment by mdutoo** [comment]
Well, for now only oasis.meta admins have the right to change project ;) 
(or I could to give you rights on this project Resource)

However, I've already created a project event_0 for you (and given you 
rights), you shouldn't need another one, or do you ?

Regards,
Marc

**Comment by divanski** [comment]
When I test inport to event_0 project, I have sam error - Access is denied (as 7aa76b4f-8233-4e8e-a24b-09c30b2dfb60).

**Comment by mdutoo** [comment]
in which env, as which user ?

users who have rights on Resources & models in event_0 project (i.e. that are in "Ozwillo Datacore event Admins" org in each env) are:
- in preprod "id":"259e3852-0f68-40ea-ae83-b734f4b01f17","name":"valery@david.bg"
- in prod  "vdachev","id":"d6ca28e4-cc13-47f4-9ef4-0d757d69d6e1"

... none are 7aa76b4f-8233-4e8e-a24b-09c30b2dfb60 that you've talked about above.

**Comment by divanski** [comment]
In preprod ... user "i_zdravkov@abv.bg"

**Comment by mdutoo** [comment]
OK, just invited this email in said org in both preprod & prod, so accept it and try again.

**Comment by divanski** [comment]
Ok. Now I have rights, but when i test import:
"Handled 4 models or mixins in 1 loops   Posted 4 models or mixins (skipped 0, no error) in 0s, browse them" and for data: "Handled 908 rows (0 errors) in 4s   Posted 0 resources (skipped 0, no error) in 0s, browse them" 
In both - no Errors... Why posted 0 resources?

**Comment by mdutoo** [comment]
Well, now at least you have successfully importer "4 models", congratulations.

Could you please provide me your models & resources CSV files (by email) so I can try myself and see what goes wrong ?

**Comment by mdutoo** [comment]
Well, after having a look at your model & resource CSVs, the reason is the most obvious one: your data CSV file's column titles are not in Internal field name nor Field name columns, that's why the tool can't find any known data to import.

So rather empty your Internal field name column, put in your data column titles value from the Field name column.

And for i18n fields ex. evntl:title only, put evntlbg:title, evntlen:title etc. in your data column titles, which requires adding the corresponding lines to the model CSV:
evntl:Location_0, evntl:title.0, , map, , , , , ,
evntl:Location_0, evntl:title.0.l, , string, , , , , , bg
evntl:Location_0, evntl:title.0.v, , string, , , , evntlfr:title, ,
evntl:Location_0, evntl:title.1, , map, , , , , ,
evntl:Location_0, evntl:title.1.l, , string, , , , , , bg
evntl:Location_0, evntl:title.1.v, , string, , , , evntlbg:title, ,
etc.
(which means: define in 0th position a map with an "l" key with default value ex. "bg" and a "v" key to import from evntlbg:title-titled data column)

Have a look at how it's done in the master model for ex. geoco:name.0.v :
https://data.ozwillo-preprod.eu/dc-ui/import/samples/master/2.21_Master_Model.csv

**Comment by mdutoo** [comment]
@divanski has recently succeeded in importing a master model-ready model and its sample data. Moreover, a possible rights problem was #150 but it has been solved. So closing this one.
