### ISSUE TITLE
Cleaner playground implementation

### ISSUE THREAD

**Issue by mdutoo** [ozwillo/ozwillo-datacore#162]

**Comment by Romathonat** [comment]
- Using React JS in order to have a clean implementation.
- Using Redux to store a global state of the application, and a clean Workflow. Redux is the most (by far) popular implementation of Flux, so it is good to use it in our project.
- Using React-Router to make routes, when clicking on menu. We could had used Redux to do that, but for every link we should had connected the currentComponent ans dispatch, wich is quite heavy. With React-Router simply putting a <Link></Link> do the job.
- Using ES6+ features so that the code will be up-to-date during some times. For example using extends React.component instead of React.createClass is better, because Facebook is going to drop createClass in the future.

**Comment by mdutoo** [comment]
Available at /dc-ui/ (linked from the description of the home swagger playground), done by @Romathonat in 71837b35a7060825a25bb3be38d3d141d8afa6af .
However, while much more pretty, it is still less complete from a functional point of view. Therefore, the old functional playground is still available at /dc-ui/index_old.html , linked from "Go to old version" in the home swagger playground.
